title: "つくって学ぶ、実装の考え方 ～麻雀編～"
summary: "どんなシステムにも共通する実装の考え方を、麻雀を実装することで確認していきます。"
topics: ["TypeScript", "麻雀"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "1"
  - example2
